---
exclude: ^CHANGELOG\.md$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-symlinks
      - id: check-ast
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-xml
      - id: check-yaml
      - id: check-toml
      - id: check-json
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        args:
          - --msg-filename
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.0.3
    hooks:
      - id: editorconfig-checker
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: check-mailmap
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.18
    hooks:
      - id: mdformat
        args:
          - --number
        additional_dependencies:
          - mdformat-gfm
          - mdformat-myst
          - mdformat-toc
          - mdformat-deflist
          - mdformat-beautysh
          - mdformat-black
          - mdformat-config
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.14.0
    hooks:
      - id: markdownlint-cli2
        additional_dependencies:
          - markdown-it-texmath@0.9.1
  - repo: https://github.com/Freed-Wu/pre-commit-hooks
    rev: 0.0.11
    hooks:
      - id: update-package.json
        args:
          - build.lua
          - package.json
